"""Энричеры (архитектура по мотивам flowsint). Импорт регистрирует их в REGISTRY."""
from . import (  # noqa: F401
    aircraft_enr,
    archive_enr,
    crypto_enr,
    domain_enr,
    email_accounts_enr,
    email_enr,
    email_leaks_enr,
    github_user_enr,
    ioc_enr,
    ip_enr,
    ip_ports_enr,
    nazk_enr,
    opendatabot_enr,
    phone_enr,
    prozorro_enr,
    ru_company_enr,
    ru_person_enr,
    typosquat_enr,
    ua_company_enr,
    ua_person_enr,
    url_secrets_enr,
    username_enr,
    vessel_enr,
    website_enr,
    whois_history_enr,
    youcontrol_enr,
)
from .base import ENTITY_TYPES, EnricherResult, enrichers_for  # noqa: F401
